language: scala
scala:
- 2.11.1
jdk:
- oraclejdk7

before_script: ./scripts/prepublish.sh
script: ./scripts/cibuild.sh

env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: RjxypYwzeOgdI5wTMbXJylavApF3gb2oCBBFy6+WxZ19iGnuEzyBP1jVCEsddVQL45JOanzSIn3WOSJfUZTUid98oWjUna1/BQ6j67LXwdMNYAXTJjzdJSmuV+3abfE4qSV865WbkeikrotTvY0CMfYdbFg8F3Ntl4Up2RaDRaE=
  - secure: YiItkHA1A5jITEwPxO/J0J70eRqNhc7+JX/Uni0ICwSES5JhEDOlNfyVEgMnCY3U5GOJfWJXVx6WvGEyVLrGJu3xvjLPb3fHeZl92ER2Oo60Q+Ewd6t38/RkU5KAsa55EEfbO2gBlwr4jYfN/GJMl+l64Y1WzeQt5LDnQpmLu9M=
  - secure: C36DzktLLfg0/CuEVECAMPIrrs+ndrczMNhacxTdbymESFbG9UhVt27tk5JJLKsykvt3+LnmpFUckEQJ38fEkyRrkD4hRRdx1r+scOyF1LoPA46oVmYunUdyMQUunbiGEVb2fRieVtlmnHhzjiO72yUCJ9zOVJAnixBrMS4/9+M=
  - secure: "YqabcvPR9z0epW+Blz26ZkJGC7EoBTTrbRTPU+6x34mrq4pf54di6xqQ1RFhj9e6U8S0ycXGwTaLgt2tQ9+rNoXcB5qSnDzky5MhEI7ps4AsmeJtfQVB7q4vIGfNU2wWVJfCo+1bJa4XySiX1sTDpsT8bMxuZ6efcdNSJ+20l9A="
  - secure: "kt1EIAL3Kt1RHpqL6x2vAOPnfpuhJhjXx/BoGj027GMYBg/YvzT/RSJIJ6hf7zyg9ymaAmaDj9sAF3XPlRx8fqRuM04JjuUsOZhqzYptqzpgsqrl9PWcVoA7Xp62knXS0UaEcN7YxJZjEe98Mkd/okeyoUWCCQOVIpgLfU0EBb0="